"""initial schema

Revision ID: 1a590dc5649e
Revises: 
Create Date: 2026-05-06 20:25:46.595066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a590dc5649e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('karyakars',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('karyakar_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('parent_karyakar_id', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.String(length=20), nullable=False),
    sa.Column('wing', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['parent_karyakar_id'], ['karyakars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('karyakar_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('xetras',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('karyakar_xetras',
    sa.Column('karyakar_id', sa.String(length=50), nullable=False),
    sa.Column('xetra_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['karyakar_id'], ['karyakars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['xetra_id'], ['xetras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('karyakar_id', 'xetra_id')
    )
    op.create_table('mandals',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('xetra_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('wing', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['xetra_id'], ['xetras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('haribhakts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('family_id', sa.String(length=50), nullable=True),
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('person_id', sa.String(length=20), nullable=False),
    sa.Column('form_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('alternate_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.String(length=10), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=False),
    sa.Column('wing', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('talent', sa.Text(), nullable=True),
    sa.Column('skill', sa.JSON(), nullable=True),
    sa.Column('vehicle', sa.JSON(), nullable=True),
    sa.Column('resident', sa.String(length=100), nullable=True),
    sa.Column('foreign_address', sa.Text(), nullable=True),
    sa.Column('dharmada_id', sa.String(length=50), nullable=True),
    sa.Column('dharmada_status', sa.String(length=20), nullable=True),
    sa.Column('satsang_karyakar', sa.String(length=100), nullable=True),
    sa.Column('satsang_since', sa.String(length=20), nullable=True),
    sa.Column('every_ekadashi', sa.String(length=10), nullable=True),
    sa.Column('last_satsang_exam', sa.String(length=50), nullable=True),
    sa.Column('ssp_passing_year', sa.String(length=10), nullable=True),
    sa.Column('ssp_number', sa.String(length=50), nullable=True),
    sa.Column('karyakar_id', sa.String(length=50), nullable=True),
    sa.Column('mandal_type', sa.String(length=50), nullable=True),
    sa.Column('special_note', sa.Text(), nullable=True),
    sa.Column('ghar_number', sa.String(length=50), nullable=True),
    sa.Column('society_name', sa.String(length=200), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('ghar_mandir', sa.String(length=5), nullable=True),
    sa.Column('arati_thai', sa.String(length=5), nullable=True),
    sa.Column('swaminarayan_prakash', sa.Boolean(), nullable=False),
    sa.Column('premvati', sa.Boolean(), nullable=False),
    sa.Column('bal_prakash', sa.Boolean(), nullable=False),
    sa.Column('bliss', sa.Boolean(), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('daily_vachnamrut', sa.String(length=20), nullable=True),
    sa.Column('daily_swami_vato', sa.Boolean(), nullable=False),
    sa.Column('ghar_sabha', sa.Boolean(), nullable=False),
    sa.Column('daily_arati', sa.Boolean(), nullable=False),
    sa.Column('daily_tilak', sa.Boolean(), nullable=False),
    sa.Column('ravisabha', sa.Boolean(), nullable=False),
    sa.Column('parasabha', sa.Boolean(), nullable=False),
    sa.Column('daily_pooja', sa.Boolean(), nullable=False),
    sa.Column('kanthi', sa.String(length=5), nullable=True),
    sa.Column('mandal_id', sa.String(length=20), nullable=False),
    sa.Column('xetra_id', sa.String(length=10), nullable=False),
    sa.Column('sampark_karyakar_id', sa.String(length=50), nullable=True),
    sa.Column('s_grade', sa.String(length=10), nullable=False),
    sa.Column('satsang_grade', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_updated_by', sa.String(length=200), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ),
    sa.ForeignKeyConstraint(['sampark_karyakar_id'], ['karyakars.id'], ),
    sa.ForeignKeyConstraint(['xetra_id'], ['xetras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('karyakar_mandals',
    sa.Column('karyakar_id', sa.String(length=50), nullable=False),
    sa.Column('mandal_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['karyakar_id'], ['karyakars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('karyakar_id', 'mandal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('karyakar_mandals')
    op.drop_table('haribhakts')
    op.drop_table('mandals')
    op.drop_table('karyakar_xetras')
    op.drop_table('xetras')
    op.drop_table('karyakars')
    op.drop_table('announcements')
    # ### end Alembic commands ###
