"""cleanup fields

Revision ID: 2743ab0cb3f9
Revises: 871d936933d2
Create Date: 2026-05-10 10:47:36.675931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2743ab0cb3f9'
down_revision = '871d936933d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('haribhakts', 'taluka')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haribhakts', sa.Column('taluka', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
