"""rename arati and thal

Revision ID: 5e983776dfa2
Revises: 2743ab0cb3f9
Create Date: 2026-05-10 11:23:05.056798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e983776dfa2'
down_revision = '2743ab0cb3f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haribhakts', sa.Column('arati', sa.String(length=50), nullable=True))
    op.add_column('haribhakts', sa.Column('thal', sa.String(length=50), nullable=True))
    op.alter_column('haribhakts', 'ghar_mandir',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_column('haribhakts', 'arati_thai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haribhakts', sa.Column('arati_thai', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.alter_column('haribhakts', 'ghar_mandir',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.drop_column('haribhakts', 'thal')
    op.drop_column('haribhakts', 'arati')
    # ### end Alembic commands ###
