"""Add satsang_grade_is_overridden flag to haribhakts

Revision ID: 6be44276a7ac
Revises: c75641229a38
Create Date: 2026-05-16 11:41:26.293339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be44276a7ac'
down_revision = 'c75641229a38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haribhakts', sa.Column('satsang_grade_is_overridden', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('haribhakts', 'is_out_of_city',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('haribhakts', 'is_nri',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('haribhakts', 'ssp_passing_year',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('haribhakts', 'satsang_grade',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               nullable=True)
    op.alter_column('haribhakts', 'transfer_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'accepted'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('haribhakts', 'transfer_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'accepted'::character varying"))
    op.alter_column('haribhakts', 'satsang_grade',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('haribhakts', 'ssp_passing_year',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('haribhakts', 'is_nri',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('haribhakts', 'is_out_of_city',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('haribhakts', 'satsang_grade_is_overridden')
    # ### end Alembic commands ###
