"""add created_at

Revision ID: 871d936933d2
Revises: 1a590dc5649e
Create Date: 2026-05-10 10:11:08.680025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871d936933d2'
down_revision = '1a590dc5649e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haribhakts', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('haribhakts', 'created_at')
    # ### end Alembic commands ###
