"""centralize vehicles

Revision ID: 9193dc198fc6
Revises: c355c3067734
Create Date: 2026-05-10 16:06:59.050051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9193dc198fc6'
down_revision = 'c355c3067734'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haribhakts', sa.Column('can_give_vehicle_in_seva', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('haribhakts', 'can_give_vehicle_in_seva')
    # ### end Alembic commands ###
