"""add ghar_sabha_details

Revision ID: c355c3067734
Revises: 5e983776dfa2
Create Date: 2026-05-10 12:45:44.609768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c355c3067734'
down_revision = '5e983776dfa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haribhakts', sa.Column('ghar_sabha_regularity', sa.String(length=20), nullable=True))
    op.add_column('haribhakts', sa.Column('ghar_sabha_days', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('haribhakts', 'ghar_sabha_days')
    op.drop_column('haribhakts', 'ghar_sabha_regularity')
    # ### end Alembic commands ###
