"""add education and occupation types

Revision ID: c75641229a38
Revises: 9193dc198fc6
Create Date: 2026-05-11 06:36:48.233082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75641229a38'
down_revision = '9193dc198fc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haribhakts', sa.Column('occupation_type', sa.String(length=50), nullable=True))
    op.add_column('haribhakts', sa.Column('education_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('haribhakts', 'education_type')
    op.drop_column('haribhakts', 'occupation_type')
    # ### end Alembic commands ###
