from sqlalchemy import Column, String, Boolean, Text, TIMESTAMP, JSON, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column
from db.base import Base

class Haribhakt(Base):
    __tablename__ = "haribhakts"
    
    id: Mapped[str] = mapped_column(String(50), primary_key=True)
    family_id: Mapped[str | None] = mapped_column(String(50), nullable=True)
    member_id: Mapped[str | None] = mapped_column(String(50), nullable=True)
    person_id: Mapped[str] = mapped_column(String(20), unique=True, nullable=False)
    form_id: Mapped[str] = mapped_column(String(20), nullable=False)
    full_name: Mapped[str] = mapped_column(String(200), nullable=False)
    father_name: Mapped[str] = mapped_column(String(100), nullable=False)
    surname: Mapped[str] = mapped_column(String(100), nullable=False)
    avatar: Mapped[str | None] = mapped_column(Text, nullable=True)
    mobile: Mapped[str] = mapped_column(String(20), nullable=False)
    whatsapp: Mapped[str] = mapped_column(String(20), nullable=False)
    alternate_number: Mapped[str | None] = mapped_column(String(20), nullable=True)
    alternate_whatsapp: Mapped[str | None] = mapped_column(String(10), nullable=True)
    email: Mapped[str] = mapped_column(String(150), nullable=False)
    area: Mapped[str] = mapped_column(String(100), nullable=False)
    city: Mapped[str] = mapped_column(String(100), nullable=False)
    pin_code: Mapped[str] = mapped_column(String(10), nullable=False)
    dob: Mapped[str] = mapped_column(String(20), nullable=False)
    wing: Mapped[str | None] = mapped_column(String(20), nullable=True)
    gender: Mapped[str | None] = mapped_column(String(10), nullable=True)
    blood_group: Mapped[str | None] = mapped_column(String(5), nullable=True)
    occupation: Mapped[str | None] = mapped_column(String(100), nullable=True)
    occupation_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    designation: Mapped[str | None] = mapped_column(String(100), nullable=True)
    business_description: Mapped[str | None] = mapped_column(Text, nullable=True)
    education: Mapped[str | None] = mapped_column(String(100), nullable=True)
    education_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    education_info: Mapped[str | None] = mapped_column(Text, nullable=True)
    talent: Mapped[str | None] = mapped_column(Text, nullable=True)
    skill: Mapped[list | None] = mapped_column(JSON, nullable=True)
    vehicle: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    can_give_vehicle_in_seva: Mapped[bool] = mapped_column(Boolean, default=False)
    is_out_of_city: Mapped[bool] = mapped_column(Boolean, default=False)
    resident: Mapped[str | None] = mapped_column(String(100), nullable=True)
    foreign_address: Mapped[str | None] = mapped_column(Text, nullable=True)
    dharmada_id: Mapped[str | None] = mapped_column(String(50), nullable=True)
    dharmada_status: Mapped[str | None] = mapped_column(String(20), nullable=True)
    satsang_karyakar: Mapped[str | None] = mapped_column(String(100), nullable=True)
    satsang_since: Mapped[str | None] = mapped_column(String(20), nullable=True)
    every_ekadashi: Mapped[str | None] = mapped_column(String(10), nullable=True)
    last_satsang_exam: Mapped[str | None] = mapped_column(String(50), nullable=True)
    karyakar_id: Mapped[str | None] = mapped_column(String(50), nullable=True)
    mandal_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    ghar_number: Mapped[str | None] = mapped_column(String(50), nullable=True)
    society_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    landmark: Mapped[str | None] = mapped_column(Text, nullable=True)
    state: Mapped[str | None] = mapped_column(String(100), nullable=True)
    country: Mapped[str | None] = mapped_column(String(100), nullable=True)
    ghar_mandir: Mapped[str | None] = mapped_column(String(10), nullable=True)
    akshar_purushottam_in_ghar_mandir: Mapped[str | None] = mapped_column(String(10), nullable=True)
    arati: Mapped[str | None] = mapped_column(String(50), nullable=True)
    thal: Mapped[str | None] = mapped_column(String(50), nullable=True)
    swaminarayan_prakash: Mapped[bool] = mapped_column(Boolean, default=False)
    premvati: Mapped[bool] = mapped_column(Boolean, default=False)
    bal_prakash: Mapped[bool] = mapped_column(Boolean, default=False)
    bliss: Mapped[bool] = mapped_column(Boolean, default=False)
    relation: Mapped[str | None] = mapped_column(String(50), nullable=True)
    daily_vachnamrut: Mapped[str | None] = mapped_column(String(20), nullable=True)
    daily_swami_vato: Mapped[bool] = mapped_column(Boolean, default=False)
    ghar_sabha: Mapped[bool] = mapped_column(Boolean, default=False)
    ghar_sabha_regularity: Mapped[str | None] = mapped_column(String(20), nullable=True)
    ghar_sabha_days: Mapped[str | None] = mapped_column(String(10), nullable=True)
    daily_arati: Mapped[bool] = mapped_column(Boolean, default=False)
    daily_tilak: Mapped[bool] = mapped_column(Boolean, default=False)
    ravisabha: Mapped[bool] = mapped_column(Boolean, default=False)
    ravisabha_regularity: Mapped[str | None] = mapped_column(String(20), nullable=True)
    parasabha: Mapped[bool] = mapped_column(Boolean, default=False)
    parasabha_regularity: Mapped[str | None] = mapped_column(String(20), nullable=True)
    daily_pooja: Mapped[bool] = mapped_column(Boolean, default=False)
    ghar_sabha_present: Mapped[str | None] = mapped_column(String(10), nullable=True)
    daily_arati_regularity: Mapped[str | None] = mapped_column(String(20), nullable=True)
    daily_arati_times: Mapped[str | None] = mapped_column(String(20), nullable=True)
    ashtak: Mapped[str | None] = mapped_column(String(20), nullable=True)
    ashtak_times: Mapped[str | None] = mapped_column(String(20), nullable=True)
    watching_cinema: Mapped[str | None] = mapped_column(String(10), nullable=True)
    eating_onion_garlic: Mapped[str | None] = mapped_column(String(10), nullable=True)
    eating_hing: Mapped[str | None] = mapped_column(String(10), nullable=True)
    eating_outside: Mapped[str | None] = mapped_column(String(10), nullable=True)
    chesta: Mapped[str | None] = mapped_column(String(20), nullable=True)
    kanthi: Mapped[str | None] = mapped_column(String(5), nullable=True)
    mandal_id: Mapped[str] = mapped_column(String(20), ForeignKey("mandals.id"))
    personal_mandal_id: Mapped[str | None] = mapped_column(String(50), nullable=True)
    xetra_id: Mapped[str] = mapped_column(String(10), ForeignKey("xetras.id"))
    sampark_karyakar_id: Mapped[str | None] = mapped_column(String(50), ForeignKey("karyakars.id"), nullable=True)
    s_grade: Mapped[str] = mapped_column(String(10))
    is_out_of_city: Mapped[bool] = mapped_column(Boolean, default=False)
    is_nri: Mapped[bool] = mapped_column(Boolean, default=False)
    status: Mapped[str] = mapped_column(String(10), default="active")
    status_reason: Mapped[str | None] = mapped_column(String(50), nullable=True)
    status_note: Mapped[str | None] = mapped_column(Text, nullable=True)
    ssp_passing_year: Mapped[str | None] = mapped_column(String(20), nullable=True)
    satsang_grade: Mapped[str | None] = mapped_column(String(10), nullable=True)
    ssp_number: Mapped[str | None] = mapped_column(String(50), nullable=True)
    special_note: Mapped[str | None] = mapped_column(Text, nullable=True)
    satsang_grade_is_overridden: Mapped[bool] = mapped_column(Boolean, default=False)
    transfer_status: Mapped[str] = mapped_column(String(20), default="accepted")
    last_updated_by: Mapped[str | None] = mapped_column(String(200), nullable=True)
    created_at: Mapped[TIMESTAMP] = mapped_column(TIMESTAMP, nullable=False, server_default=func.now())
    last_updated_at: Mapped[TIMESTAMP | None] = mapped_column(TIMESTAMP, nullable=True, onupdate=func.now())
